# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import p1on.proto.properties_pb2 as properties__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntext.proto\x12\x04p1on\x1a\x10properties.proto\"\xb5\x01\n\x04Text\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05group\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\n \x01(\t\x12$\n\x08position\x18\x0b \x01(\x0e\x32\x12.p1on.TextPosition\x12&\n\x08\x66ontSize\x18\x0c \x01(\x0b\x32\x14.p1on.ScalarProperty\x12\x0c\n\x04\x62old\x18\r \x01(\x08\x12\x0e\n\x06italic\x18\x0e \x01(\x08*\x86\x01\n\x0cTextPosition\x12\n\n\x06\x43\x45NTER\x10\x00\x12\x0f\n\x0bUPPER_RIGHT\x10\x01\x12\x07\n\x03TOP\x10\x02\x12\x0e\n\nUPPER_LEFT\x10\x03\x12\x08\n\x04LEFT\x10\x04\x12\x0e\n\nLOWER_LEFT\x10\x05\x12\n\n\x06\x42OTTOM\x10\x06\x12\x0f\n\x0bLOWER_RIGHT\x10\x07\x12\t\n\x05RIGHT\x10\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXTPOSITION._serialized_start=223
  _TEXTPOSITION._serialized_end=357
  _TEXT._serialized_start=39
  _TEXT._serialized_end=220
# @@protoc_insertion_point(module_scope)
