# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animatible.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import wilson.proto.line_pb2 as line__pb2
import wilson.proto.overlay_pb2 as overlay__pb2
import wilson.proto.prism_pb2 as prism__pb2
import wilson.proto.sphere_pb2 as sphere__pb2
import wilson.proto.tube_pb2 as tube__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61nimatible.proto\x12\x06wilson\x1a\nline.proto\x1a\roverlay.proto\x1a\x0bprism.proto\x1a\x0csphere.proto\x1a\ntube.proto\"\xed\x01\n\nAnimatible\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06groups\x18\x02 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12 \n\x06sphere\x18\x10 \x01(\x0b\x32\x0e.wilson.SphereH\x00\x12\x1c\n\x04line\x18\x11 \x01(\x0b\x32\x0c.wilson.LineH\x00\x12\x1c\n\x04tube\x18\x12 \x01(\x0b\x32\x0c.wilson.TubeH\x00\x12\"\n\x07overlay\x18\x13 \x01(\x0b\x32\x0f.wilson.OverlayH\x00\x12\x1e\n\x05prism\x18\x14 \x01(\x0b\x32\r.wilson.PrismH\x00\x42\n\n\x08instanceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'animatible_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ANIMATIBLE._serialized_start=95
  _ANIMATIBLE._serialized_end=332
# @@protoc_insertion_point(module_scope)
