"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
from wilson.proto import vector_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Camera(google.protobuf.message.Message):
    """Virtual camera dictating the point of view rendered in 3D mode"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POSITION_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    @property
    def position(self) -> vector_pb2.Vector:
        """position of camera"""
    @property
    def target(self) -> vector_pb2.Vector:
        """target the camera looks at"""
    def __init__(
        self,
        *,
        position: vector_pb2.Vector | None = ...,
        target: vector_pb2.Vector | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["position", b"position", "target", b"target"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["position", b"position", "target", b"target"]) -> None: ...

global___Camera = Camera
