# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interpolation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13interpolation.proto\x12\x06wilson*:\n\rInterpolation\x12\n\n\x06LINEAR\x10\x00\x12\x08\n\x04HOLD\x10\x01\x12\t\n\x05\x41HEAD\x10\x02\x12\x08\n\x04STEP\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interpolation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INTERPOLATION._serialized_start=31
  _INTERPOLATION._serialized_end=89
# @@protoc_insertion_point(module_scope)
