# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: overlay.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import wilson.proto.properties_pb2 as properties__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\roverlay.proto\x12\x06wilson\x1a\x10properties.proto\"\x87\x01\n\x07Overlay\x12\x0c\n\x04text\x18\x01 \x01(\t\x12&\n\x08position\x18\x02 \x01(\x0e\x32\x14.wilson.TextPosition\x12(\n\x08\x66ontSize\x18\x03 \x01(\x0b\x32\x16.wilson.ScalarProperty\x12\x0c\n\x04\x62old\x18\x04 \x01(\x08\x12\x0e\n\x06italic\x18\x05 \x01(\x08*\x86\x01\n\x0cTextPosition\x12\n\n\x06\x43\x45NTER\x10\x00\x12\x0f\n\x0bUPPER_RIGHT\x10\x01\x12\x07\n\x03TOP\x10\x02\x12\x0e\n\nUPPER_LEFT\x10\x03\x12\x08\n\x04LEFT\x10\x04\x12\x0e\n\nLOWER_LEFT\x10\x05\x12\n\n\x06\x42OTTOM\x10\x06\x12\x0f\n\x0bLOWER_RIGHT\x10\x07\x12\t\n\x05RIGHT\x10\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'overlay_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXTPOSITION._serialized_start=182
  _TEXTPOSITION._serialized_end=316
  _OVERLAY._serialized_start=44
  _OVERLAY._serialized_end=179
# @@protoc_insertion_point(module_scope)
