# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: path.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import wilson.proto.interpolation_pb2 as interpolation__pb2
import wilson.proto.vector_pb2 as vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npath.proto\x12\x06wilson\x1a\x13interpolation.proto\x1a\x0cvector.proto\"\xab\x01\n\x04Path\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\r\x12\"\n\x06points\x18\x03 \x03(\x0b\x32\x12.wilson.Path.Point\x12,\n\rinterpolation\x18\x04 \x01(\x0e\x32\x15.wilson.Interpolation\x1a\x37\n\x05Point\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12 \n\x08position\x18\x02 \x01(\x0b\x32\x0e.wilson.Vectorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'path_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PATH._serialized_start=58
  _PATH._serialized_end=229
  _PATH_POINT._serialized_start=174
  _PATH_POINT._serialized_end=229
# @@protoc_insertion_point(module_scope)
