# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prism.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import wilson.proto.properties_pb2 as properties__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bprism.proto\x12\x06wilson\x1a\x10properties.proto\"\x8c\x02\n\x05Prism\x12(\n\x08position\x18\x01 \x01(\x0b\x32\x16.wilson.VectorProperty\x12&\n\x06normal\x18\x02 \x01(\x0b\x32\x16.wilson.VectorProperty\x12(\n\x08rotation\x18\x03 \x01(\x0b\x32\x16.wilson.ScalarProperty\x12&\n\x06radius\x18\x04 \x01(\x0b\x32\x16.wilson.ScalarProperty\x12&\n\x06height\x18\x05 \x01(\x0b\x32\x16.wilson.ScalarProperty\x12\x11\n\tnVertices\x18\x06 \x01(\r\x12$\n\x05\x63olor\x18\x07 \x01(\x0b\x32\x15.wilson.ColorPropertyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prism_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRISM._serialized_start=42
  _PRISM._serialized_end=310
# @@protoc_insertion_point(module_scope)
