"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
from wilson.proto import (
    camera_pb2,
    colormap_pb2,
    graph_pb2,
    line_pb2,
    meta_pb2,
    overlay_pb2,
    path_pb2,
    sphere_pb2,
    tube_pb2
)

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Project(google.protobuf.message.Message):
    """Root container for all animation relevant data"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    GRAPHS_FIELD_NUMBER: builtins.int
    PATHS_FIELD_NUMBER: builtins.int
    COLORMAP_FIELD_NUMBER: builtins.int
    CAMERA_FIELD_NUMBER: builtins.int
    HIDDENGROUPS_FIELD_NUMBER: builtins.int
    SPHERES_FIELD_NUMBER: builtins.int
    LINES_FIELD_NUMBER: builtins.int
    TUBES_FIELD_NUMBER: builtins.int
    OVERLAYS_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> meta_pb2.ProjectMeta:
        """Meta information"""
    @property
    def graphs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[graph_pb2.Graph]:
        """-----------------------Data--------------------------

        list of graphs
        """
    @property
    def paths(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[path_pb2.Path]:
        """list of paths"""
    @property
    def colormap(self) -> colormap_pb2.ColorMap:
        """global color map"""
    @property
    def camera(self) -> camera_pb2.Camera:
        """-----------------------Scene-------------------------

        Overrides standard camera if provided
        """
    @property
    def hiddenGroups(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """---------------------Animation-----------------------

        list of groups hidden by default
        """
    @property
    def spheres(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[sphere_pb2.Sphere]:
        """list of animated spheres"""
    @property
    def lines(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[line_pb2.Line]:
        """list of animated lines"""
    @property
    def tubes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[tube_pb2.Tube]:
        """list of animated tubes"""
    @property
    def overlays(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[overlay_pb2.Overlay]:
        """list of animated overlay text"""
    def __init__(
        self,
        *,
        meta: meta_pb2.ProjectMeta | None = ...,
        graphs: collections.abc.Iterable[graph_pb2.Graph] | None = ...,
        paths: collections.abc.Iterable[path_pb2.Path] | None = ...,
        colormap: colormap_pb2.ColorMap | None = ...,
        camera: camera_pb2.Camera | None = ...,
        hiddenGroups: collections.abc.Iterable[builtins.str] | None = ...,
        spheres: collections.abc.Iterable[sphere_pb2.Sphere] | None = ...,
        lines: collections.abc.Iterable[line_pb2.Line] | None = ...,
        tubes: collections.abc.Iterable[tube_pb2.Tube] | None = ...,
        overlays: collections.abc.Iterable[overlay_pb2.Overlay] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["camera", b"camera", "colormap", b"colormap", "meta", b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["camera", b"camera", "colormap", b"colormap", "graphs", b"graphs", "hiddenGroups", b"hiddenGroups", "lines", b"lines", "meta", b"meta", "overlays", b"overlays", "paths", b"paths", "spheres", b"spheres", "tubes", b"tubes"]) -> None: ...

global___Project = Project
