# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: project.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import wilson.proto.camera_pb2 as camera__pb2
import wilson.proto.meta_pb2 as meta__pb2
import wilson.proto.graph_pb2 as graph__pb2
import wilson.proto.path_pb2 as path__pb2
import wilson.proto.colormap_pb2 as colormap__pb2
import wilson.proto.line_pb2 as line__pb2
import wilson.proto.sphere_pb2 as sphere__pb2
import wilson.proto.tube_pb2 as tube__pb2
import wilson.proto.overlay_pb2 as overlay__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproject.proto\x12\x06wilson\x1a\x0c\x63\x61mera.proto\x1a\nmeta.proto\x1a\x0bgraph.proto\x1a\npath.proto\x1a\x0e\x63olormap.proto\x1a\nline.proto\x1a\x0csphere.proto\x1a\ntube.proto\x1a\roverlay.proto\"\xc0\x02\n\x07Project\x12!\n\x04meta\x18\x01 \x01(\x0b\x32\x13.wilson.ProjectMeta\x12\x1d\n\x06graphs\x18\x02 \x03(\x0b\x32\r.wilson.Graph\x12\x1b\n\x05paths\x18\x03 \x03(\x0b\x32\x0c.wilson.Path\x12\"\n\x08\x63olormap\x18\x05 \x01(\x0b\x32\x10.wilson.ColorMap\x12\x1e\n\x06\x63\x61mera\x18\n \x01(\x0b\x32\x0e.wilson.Camera\x12\x14\n\x0chiddenGroups\x18\x0f \x03(\t\x12\x1f\n\x07spheres\x18\x10 \x03(\x0b\x32\x0e.wilson.Sphere\x12\x1b\n\x05lines\x18\x11 \x03(\x0b\x32\x0c.wilson.Line\x12\x1b\n\x05tubes\x18\x12 \x03(\x0b\x32\x0c.wilson.Tube\x12!\n\x08overlays\x18\x13 \x03(\x0b\x32\x0f.wilson.Overlayb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROJECT._serialized_start=146
  _PROJECT._serialized_end=466
# @@protoc_insertion_point(module_scope)
