# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: project.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import wilson.proto.camera_pb2 as camera__pb2
import wilson.proto.meta_pb2 as meta__pb2
import wilson.proto.graph_pb2 as graph__pb2
import wilson.proto.path_pb2 as path__pb2
import wilson.proto.colormap_pb2 as colormap__pb2
import wilson.proto.animatible_pb2 as animatible__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproject.proto\x12\x06wilson\x1a\x0c\x63\x61mera.proto\x1a\nmeta.proto\x1a\x0bgraph.proto\x1a\npath.proto\x1a\x0e\x63olormap.proto\x1a\x10\x61nimatible.proto\"\xeb\x01\n\x07Project\x12!\n\x04meta\x18\x01 \x01(\x0b\x32\x13.wilson.ProjectMeta\x12\x1d\n\x06graphs\x18\x02 \x03(\x0b\x32\r.wilson.Graph\x12\x1b\n\x05paths\x18\x03 \x03(\x0b\x32\x0c.wilson.Path\x12\"\n\x08\x63olormap\x18\x05 \x01(\x0b\x32\x10.wilson.ColorMap\x12\x1e\n\x06\x63\x61mera\x18\n \x01(\x0b\x32\x0e.wilson.Camera\x12\x14\n\x0chiddenGroups\x18\x0f \x03(\t\x12\'\n\x0b\x61nimatibles\x18\x10 \x03(\x0b\x32\x12.wilson.Animatibleb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROJECT._serialized_start=111
  _PROJECT._serialized_end=346
# @@protoc_insertion_point(module_scope)
