# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: properties.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import wilson.proto.color_pb2 as color__pb2
import wilson.proto.vector_pb2 as vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10properties.proto\x12\x06wilson\x1a\x0b\x63olor.proto\x1a\x0cvector.proto\"C\n\x0eScalarProperty\x12\x14\n\nconstValue\x18\x01 \x01(\x01H\x00\x12\x11\n\x07graphId\x18\x02 \x01(\rH\x00\x42\x08\n\x06source\"R\n\x0eVectorProperty\x12$\n\nconstValue\x18\x01 \x01(\x0b\x32\x0e.wilson.VectorH\x00\x12\x10\n\x06pathId\x18\x02 \x01(\rH\x00\x42\x08\n\x06source\"h\n\rColorProperty\x12#\n\nconstValue\x18\x01 \x01(\x0b\x32\r.wilson.ColorH\x00\x12\x11\n\x07graphId\x18\x02 \x01(\rH\x00\x12\x15\n\x0bscalarValue\x18\x03 \x01(\x01H\x00\x42\x08\n\x06sourceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'properties_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCALARPROPERTY._serialized_start=55
  _SCALARPROPERTY._serialized_end=122
  _VECTORPROPERTY._serialized_start=124
  _VECTORPROPERTY._serialized_end=206
  _COLORPROPERTY._serialized_start=208
  _COLORPROPERTY._serialized_end=312
# @@protoc_insertion_point(module_scope)
