"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
from wilson.proto import properties_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Sphere(google.protobuf.message.Message):
    """Animatible sphere in 3D space"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    GROUPS_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    COLOR_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    RADIUS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Name as shown in explorer"""
    @property
    def groups(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Name of groups this belongs to"""
    description: builtins.str
    """Additional text shown when selected"""
    @property
    def color(self) -> properties_pb2.ColorProperty:
        """Color"""
    @property
    def position(self) -> properties_pb2.VectorProperty:
        """center of sphere"""
    @property
    def radius(self) -> properties_pb2.ScalarProperty:
        """Radius"""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        groups: collections.abc.Iterable[builtins.str] | None = ...,
        description: builtins.str = ...,
        color: properties_pb2.ColorProperty | None = ...,
        position: properties_pb2.VectorProperty | None = ...,
        radius: properties_pb2.ScalarProperty | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["color", b"color", "position", b"position", "radius", b"radius"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["color", b"color", "description", b"description", "groups", b"groups", "name", b"name", "position", b"position", "radius", b"radius"]) -> None: ...

global___Sphere = Sphere
