"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
from wilson.proto import properties_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Sphere(google.protobuf.message.Message):
    """Animatible sphere in 3D space"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POSITION_FIELD_NUMBER: builtins.int
    RADIUS_FIELD_NUMBER: builtins.int
    COLOR_FIELD_NUMBER: builtins.int
    @property
    def position(self) -> properties_pb2.VectorProperty:
        """center of sphere"""
    @property
    def radius(self) -> properties_pb2.ScalarProperty:
        """Radius"""
    @property
    def color(self) -> properties_pb2.ColorProperty:
        """Color"""
    def __init__(
        self,
        *,
        position: properties_pb2.VectorProperty | None = ...,
        radius: properties_pb2.ScalarProperty | None = ...,
        color: properties_pb2.ColorProperty | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["color", b"color", "position", b"position", "radius", b"radius"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["color", b"color", "position", b"position", "radius", b"radius"]) -> None: ...

global___Sphere = Sphere
