name: Continuous Integration
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build:
    name: Build and Deploy App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x      
      - name: Run Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Linting
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
      - name: Build App
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Build Docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      - name: Move Docs
        run: |
          mkdir dist/docs
          cp -a docs/build/html/. dist/docs/
      - name: Create .nojekyll
        run: |
          touch dist/.nojekyll
      - name: Copy Example Events
        run: |
          cp examples/tutorial.wlsn dist/tutorial
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
