name: Test
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Run Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Linting
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
      - name: Build App
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Build Docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
